subo agregado a js de botones de pagina de subastas y modificaion en …
rpgrca/proyecto-ispc-fullstack pull request #225
Opened 2022-10-23 18:23 UTC by NataliaAlvarezIspc

…subastas.html

2022-10-23 22:47 UTC, rpgrca requested changes
Pusiste las funciones en el JS, sin embargo si yo tomo el JS directamente y veo la función boton1 no me dice nada. El nombre de la función debería dar a entender qué es lo que hace y dónde, entonces mejor que boton1, boton2 y boton3 diría que subir_puja_un_poco, subir_puja_mas y subir_puja_mucho_mas por poner un ejemplo me daría la idea de qué es lo que hace cada función y dónde la están usando. Si cada uno escribe en un JS compartido boton1, boton2, boton3, boton4, boton5 el archivo se vuelve confuso.

2022-10-24 00:05 UTC, NataliaAlvarezIspc commented
Tenés razón... Ahora lo arreglo

2022-10-24 02:58 UTC, NataliaAlvarezIspc commented
modificado desde aquí

2022-10-24 02:58 UTC, rpgrca approved these changes

2022-10-24 02:59 UTC, merged