agregado min y maxlength a registro html
rpgrca/proyecto-ispc-fullstack pull request #276
Opened 2022-11-05 20:41 UTC by NataliaAlvarezIspc

2022-11-06 14:45 UTC, rpgrca requested changes
En teoría el mail más corto podría ser a@a.to que tendría 6 letras, no 10 como pusiste. El min length para nombre y apellido debería ser 1, no 2, podrías poner tu inicial únicamente. El minlength de la clave debería ser 6 que es el que usé para los datos de prueba para no tener que cambiar por todos lados. Y no estoy seguro de la fecha de nacimiento, habría que poner una advertencia que solo los mayores de 18 pueden usar el sitio.

2022-11-06 15:24 UTC, NataliaAlvarezIspc commented
ok, en un rato lo modifico... En cuanto a la fecha de nacimiento, así como está ahora no se puede poner una fecha posterior a noviembre de 2004. Me parece que no tiene sentido poner un cartelito si luego pueden ingresar cualquier fecha

2022-11-06 15:34 UTC, NataliaAlvarezIspc commented
le puedo agregar "(solo mayores de 18 años)" al lado de "Fecha de nacimiento"

2022-11-06 18:13 UTC, NataliaAlvarezIspc commented
Ya subi las correcciones. Decime si está bien así o le modifico algo más.

2022-11-07 01:33 UTC, rpgrca approved these changes
Hay que poner un texto para aclarar que solo mayores de 18 años pueden inscribirse con tu fecha máxima de nacimiento.

2022-11-07 01:33 UTC, merged